project:
  type: website
  output-dir: docs

website:
  title: "Verrucomicrobiota Project"
  navbar:
    left:
      - href: index.qmd
        text: Theme
      - href: Abstract.qmd
        text: Abstract
      - href: Methods.qmd
        text: Methods
      - href: Results.qmd
        text: Results
      - href: Discussion.qmd
        text: Discussion
      - href: Conclusion.qmd
        text: Conclusion


format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

