---
title: "Abstract"
---

Verrucomicrobiotga are present in almost all soil, but it was originally thought to be at low frequencies since there were only a few studies that focused on the verrucomicrobia quantities. However, with ecological data from The National Ecological Observatory Network (NEON), funded by the National Science Foundation, more data has surfaced, providing information about the bacteria across ecosystems, with data focusing on Niwot Ridge, Colorado. With the increasing temperatures due to global warming, it is important to take notice of the different bacteria that are growing and changing along with the climate. Where they require very specific environments to grow, taking notice of the different features of existing environments is massively important. In the near future where climates might not be able to keep the bacteria alive, it would be vital to provide a possible man made environment that can facilitate the bacteria growth with the data collected, allowing for a deeper understanding of the bacteria. 

# Motivating Reasons

Bacteria play many important roles in the soil of ecosystem such as providing soil structure, soil aggregation, recycling of soil nutrients, and water recycling. They also serve an important function in breaking down organic residues, carbon compounds and simple sugars, as well as taking up nutrients into their cell membranes such as nitrogen  (Hoorman, 2016). These functions are important for plant growth and maintaining a healthy ecosystem, i.e. continuous recycling of nutrients, maintaining a balance of pathogenic and non-pathogenic bacterial species, and soil stability. The phylum of bacteria Verrucromicrobiota are widespread and while the research surrounding their functions is limited it is thought that they play a major role in carbon degeneration and have a greater ability to survive in a variety of conditions than previously thought. Just like other bacteria, Verrucromicrobiota must be able to adapt to the diverse microenvironments of the soil in order to provide these ecological benefits, and with increasing global temperatures that generally raise microbial activity and in turn decrease the amount of organic matter in soil (Ruan, 2023) it will be important to monitor their abundance in different ecosystems across time.

# Introduction

The National Ecological Observatory Network (NEON) funded by the National Science Foundation is a large, continental-scale project with the purpose of collecting long-term open access ecological data at various sites throughout the United States including Hawaii and Puerto Rico. This data enables researchers to conduct studies addressing questions related to important environmental challenges. The NEON database includes information on freshwater ecosystems such as rivers and streams as well as terrestrial ecosystems ranging from mountainous tundra to tropical rainforests. We are particularly interested in the microbe metagenome sequence data that NEON has collected which includes metagenome-assembled genomes (MAGs) of various phylums and orders of bacteria at different sites across the United States. For our specific project, we focus on the NEON project site located in the Niwot Ridge in Boulder, Colorado (NIWO), and the bacteria Verrucromicorbiota. In our study, we are using NEON data from the NIWO site to explore the relationship between Verrucormicriobiota abundance and soil conditions, and we explore how this relationship impacts Verrucomicrobiota growth and what this could mean for the ecosystems the bacteria inhabits.

Verrucomicrobia is a free living, widespread phylum of bacteria surviving in freshwater, marine, terrestrial soil, and animal gut, and are significant contributors to carbon cycling. Despite their prevalence, they are underrepresented in databases, limiting our understanding of their ecological roles. Recent findings highlight Verrucomicrobia's role as specialist organic polymer degraders capable of adapting to diverse environmental conditions, expanding our understanding of their ecological significance (Nixon, 2019). 

-   Verrucomicrobiota

    -   Free living bacteria (not dependent on other organisms for survival)

    -   Can survive in a variety of ecosystems: freshwater, marine, terrestrial soil, animal gut 

    -   Metagenome analysis suggests “potential role as polysaccharide degraders in freshwater” \[Fuerst, 2019\]

    -   average 23% of all bacterial sequences present in the microbial communities (Bergmann et al., 2011)

    -   This bacteria has possible associations with 

    -   Bacteria found in mucus lining of guts, high abundance in adults, aids in glucose homeostasis

    -   Associated with the algae bloom onset
