---
title: "Discussion"
---

# Environmental Data

We found that, overall, Verrucomicrobiota is a phylum that is found under many different environmental conditions. There were wide spreads of distribution across soil temperature and pH, but the most common conditions were temperatures between 10 and 20 degrees celsius and pH values between 6 and 7. This observation mirrors that of the overall studied MAGs. Verrucomicrobiota were found in 6 different ecosystem subtypes, and these locations were well-distributed throughout their phylogeny. Interestingly, for soil nutrients Verrucomicrobiota tended to be at the high and low ends, but not the middle, of the spectra for both nitrogen and organic carbon amounts, but both of these observations may have been influenced by sample size. Finally, the phylum was found at a variety of different depths, but the most common by far was 0.10 meters (although this is also likely influenced by the types of sampling). Overall, this would imply that Verrucomicrobiota is able to adapt to many different environments, perhaps meaning that they could resist environmental changes.

We also expanded our study of environmental data into different sites, focusing on Niwot Ridge but also examining the other NEON sites due to a lack of data available for Niwot. We found correlations between soil temperature and elevation at Niwot Ridge but not for all sites, as well as a weak one between soil temperature and pH over all NEON sites. The different ecosystem subtypes had different average temperatures which was to be expected. Niwot Ridge was determined to be fully Terrestrial Soil, with a fairly even split between mineral and organic soil samples and a variety of elevations.

# Genome and Assembly Data

In addition to environmental factors we looked into the genomic properties of the Verrucomicrobiota included in this study. There was a clear relationship between genome size and gene count, which was to be expected. Genome size varied slightly between orders of Verrucomicrobiota, but dramatically between genera, with JAFAMB01 having the largest genomes. There was also variety in 16s rRNA counts and tRNA counts. Several novel species of Verrucomicrobiota were discovered, with most of them being of the order Chthoniobacterales For their assemblies, there was not a noticeable relationship between scaffold count, bin completeness, and genome size, and a majority of the samples were of medium bin quality.

At Niwot Ridge, like the total data set, there was a variety of genome sizes and phyla. The most common phylum was Pseudomonadota, and Verrucomicrobiota was the fourth most common type. Of novel bacteria, most were Actinomycetota with Verrucomicrobiota a close second.

Looking at the overall data, there was a wide distribution of genome sizes, but a large majority were less than 5 million bases. Novel bacteria were found at all the sites, but the most common place to find novel species was in the combined assemblies. Of these novel bacteria, most were of the phylum Actinomycetota, and Verrucomicrobiota had an intermediate number. These results suggest that sampling NEON sites, including Niwot Ridge, can provide a variety of information and can contribute new genera and species, which is both exciting and useful for scientific work.

# Project Limitations and Next Steps

This project was significantly limited by a lack of available data for both our phylum and, especially, for our site. For example, in our graph comparing soil temperature and pH at Niwot Ridge, there are only 6 points because very few environmental readings were done at our site. We also were unable to explore other factors that would have been of interest, such as chlorophyll concentration, algal bloom, and other soil nutrients such as sulfur (which is especially relevant to Verrucomicrobiota species). Future studies could investigate these factors as well as following environmental trends over time. All of this could increase our understanding of Verrucomicrobiota and other phyla’s roles in different ecosystems.

\
